# Generated by Django 2.2.3 on 2019-07-14 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('project_type', models.TextField(choices=[('book', 'book'), ('article', 'article'), ('short_story', 'short_story'), ('short_piece', 'short_piece'), ('poem', 'poem')], default='book', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='blocks')),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.Project')),
            ],
        ),
    ]
